# Generated by Django 5.1.6 on 2025-02-22 00:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('images', models.TextField(blank=True, null=True)),
                ('rent_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('furnished', models.BooleanField(default=False)),
                ('total_vacancy', models.PositiveIntegerField()),
                ('available_vacancy', models.PositiveIntegerField()),
                ('sharing', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('custom_features', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
